[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = 'self.config.blind = blind or {}'
position = "before"
payload = """
if G.GAME.modifiers.cm_decreasing_handsize and self:get_type() == 'Boss' then
  G.hand:change_size(-G.GAME.modifiers.cm_decreasing_handsize)
end
"""
match_indent = true
overwrite = false