[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.unused_discards = (G.GAME.unused_discards or 0) + G.GAME.current_round.discards_left"
position = "after"
payload = """
if G.GAME.modifiers.dm_last_ante_hand then
G.GAME.modifiers.dm_ante_hand_counter = G.GAME.modifiers.dm_ante_hand_counter + G.GAME.modifiers.dm_last_ante_hand*G.GAME.current_round.hands_left
end"""
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.blind:get_type() == 'Boss' then"
position = "before"
payload = """
if G.GAME.modifiers.dm_last_ante_hand and G.GAME.blind:get_type() == 'Boss' then
ease_dollars(G.GAME.modifiers.dm_ante_hand_counter)
G.GAME.modifiers.dm_ante_hand_counter = 0
end"""
match_indent = true
overwrite = false