[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "set_voucher_usage(self)"
position = "after"
payload = """
if G.GAME.modifiers.dm_restock_consumeables then
if G.GAME.used_vouchers["v_tarot_merchant"] then G.GAME.tarot_rate = 1 end
if G.GAME.used_vouchers["v_planet_merchant"] then G.GAME.planet_rate = 1 end
end
"""
match_indent = true
overwrite = false